/**
 * Generic client-side document exporter.
 * Renders a print-styled window (Save as PDF) or downloads plain markdown —
 * no PDF library required, works on mobile & desktop.
 */

export type DocSection =
  | { heading: string; type: "list"; items: string[] }
  | { heading: string; type: "text"; items: string[] }
  | { heading: string; type: "formula"; items: string[] }
  | { heading: string; type: "kv"; items: { term: string; definition: string }[] }
  | {
      heading: string;
      type: "qa";
      items: { question: string; answer: string; meta?: string }[];
    };

const esc = (s: string) =>
  String(s ?? "").replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!),
  );

function renderSection(s: DocSection): string {
  const head = `<h2>${esc(s.heading)}</h2>`;
  switch (s.type) {
    case "list":
      if (!s.items?.length) return "";
      return head + `<ul>${s.items.map((i) => `<li>${esc(i)}</li>`).join("")}</ul>`;
    case "text":
      if (!s.items?.length) return "";
      return head + s.items.map((i) => `<p>${esc(i)}</p>`).join("");
    case "formula":
      if (!s.items?.length) return "";
      return head + s.items.map((i) => `<div class="formula">${esc(i)}</div>`).join("");
    case "kv":
      if (!s.items?.length) return "";
      return (
        head +
        s.items
          .map((t) => `<div class="term"><b>${esc(t.term)}</b>${esc(t.definition)}</div>`)
          .join("")
      );
    case "qa":
      if (!s.items?.length) return "";
      return (
        head +
        s.items
          .map(
            (q, i) => `<div class="qa">
              ${q.meta ? `<span class="meta">${esc(q.meta)}</span>` : ""}
              <div class="q">${i + 1}. ${esc(q.question)}</div>
              ${q.answer ? `<div class="a"><b>Ans.</b> ${esc(q.answer)}</div>` : ""}
            </div>`,
          )
          .join("")
      );
    default:
      return "";
  }
}

/** Real .pdf file download using jsPDF (no popup / print dialog needed). */
export async function exportDocPdf(opts: {
  title: string;
  subtitle?: string;
  sections: DocSection[];
}) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const M = 48;
  const maxW = pageW - M * 2;
  let y = M;

  const newPageIfNeeded = (h: number) => {
    if (y + h > pageH - M) {
      doc.addPage();
      y = M;
    }
  };

  const write = (
    text: string,
    { size = 11, style = "normal", indent = 0, gap = 5, color = [17, 17, 17] as number[] } = {},
  ) => {
    doc.setFont("helvetica", style);
    doc.setFontSize(size);
    doc.setTextColor(color[0], color[1], color[2]);
    const lines = doc.splitTextToSize(String(text ?? ""), maxW - indent);
    for (const line of lines) {
      newPageIfNeeded(size + gap);
      doc.text(line, M + indent, y);
      y += size + gap - 2;
    }
    y += gap;
  };

  // Header
  write(opts.title, { size: 18, style: "bold", gap: 4 });
  if (opts.subtitle) write(opts.subtitle, { size: 10, color: [110, 110, 110], gap: 6 });
  doc.setDrawColor(20, 20, 20);
  doc.line(M, y, pageW - M, y);
  y += 18;

  for (const s of opts.sections) {
    if (!s.items?.length) continue;
    newPageIfNeeded(40);
    write(s.heading.toUpperCase(), { size: 12, style: "bold", gap: 8 });

    if (s.type === "list") {
      s.items.forEach((i) => write(`•  ${i}`, { indent: 8 }));
    } else if (s.type === "text") {
      s.items.forEach((i) => write(i));
    } else if (s.type === "formula") {
      s.items.forEach((i) => {
        doc.setFont("courier", "normal");
        write(i, { size: 11, indent: 8 });
      });
    } else if (s.type === "kv") {
      s.items.forEach((t) => {
        write(t.term, { size: 11, style: "bold", gap: 2 });
        write(t.definition, { size: 11, indent: 8 });
      });
    } else if (s.type === "qa") {
      s.items.forEach((q, i) => {
        if (q.meta) write(q.meta, { size: 9, color: [90, 90, 140], gap: 2 });
        write(`${i + 1}. ${q.question}`, { size: 11, style: "bold", gap: 3 });
        if (q.answer) write(`Ans. ${q.answer}`, { size: 11, indent: 10, color: [55, 65, 81] });
      });
    }
    y += 6;
  }

  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Generated by Edspire Lens · ${new Date().toLocaleDateString()}  ·  ${p}/${pages}`,
      pageW / 2,
      pageH - 22,
      { align: "center" },
    );
  }

  doc.save(`${safeName(opts.title)}.pdf`);
}

const safeName = (t: string) => t.replace(/[^\w\d -]/g, "").trim().slice(0, 60) || "edspire-notes";

/** Legacy printable-window export (kept as a fallback). */
export function exportDocPrintable(opts: {
  title: string;
  subtitle?: string;
  sections: DocSection[];
}) {
  const win = window.open("", "_blank", "noopener,noreferrer,width=860,height=940");
  if (!win) return;

  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8" />
<title>${esc(opts.title)}</title>
<style>
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color:#111; margin:0; padding:32px; line-height:1.55; }
  header { border-bottom:2px solid #111; padding-bottom:10px; margin-bottom:22px; }
  h1 { font-size:22px; margin:0; }
  .subtitle { font-size:12px; color:#666; margin-top:4px; }
  h2 { font-size:13px; text-transform:uppercase; letter-spacing:0.09em; margin:22px 0 8px; color:#222; border-left:3px solid #111; padding-left:8px; page-break-after:avoid; }
  ul { margin:0; padding-left:20px; }
  li, p { margin:0 0 6px; font-size:13px; }
  .formula { font-family:"SFMono-Regular", Menlo, monospace; background:#f4f4f5; border:1px solid #e4e4e7; border-radius:6px; padding:6px 10px; margin:4px 0; font-size:13px; }
  .term { margin-bottom:10px; font-size:13px; }
  .term b { display:block; margin-bottom:2px; }
  .qa { margin-bottom:12px; page-break-inside:avoid; font-size:13px; }
  .qa .meta { display:inline-block; font-size:10px; letter-spacing:.06em; text-transform:uppercase; background:#eef2ff; color:#3730a3; border-radius:99px; padding:2px 8px; margin-bottom:4px; }
  .qa .q { font-weight:600; }
  .qa .a { color:#374151; margin-top:3px; }
  footer { margin-top:34px; font-size:10px; color:#888; text-align:center; }
  @media print { body { padding:14mm; } }
</style></head>
<body>
  <header>
    <h1>${esc(opts.title)}</h1>
    ${opts.subtitle ? `<div class="subtitle">${esc(opts.subtitle)}</div>` : ""}
  </header>
  ${opts.sections.map(renderSection).join("")}
  <footer>Generated by Edspire Lens · ${new Date().toLocaleDateString()}</footer>
  <script>window.addEventListener("load",()=>setTimeout(()=>window.print(),300));</script>
</body></html>`;

  win.document.open();
  win.document.write(html);
  win.document.close();
}

/** Download the same content as a .md file for offline use. */
export function exportDocMarkdown(opts: { title: string; subtitle?: string; sections: DocSection[] }) {
  const lines: string[] = [`# ${opts.title}`];
  if (opts.subtitle) lines.push(`_${opts.subtitle}_`);
  for (const s of opts.sections) {
    if (!s.items?.length) continue;
    lines.push(`\n## ${s.heading}\n`);
    if (s.type === "list") lines.push(...s.items.map((i) => `- ${i}`));
    else if (s.type === "text") lines.push(...s.items.map((i) => `${i}\n`));
    else if (s.type === "formula") lines.push(...s.items.map((i) => `\`${i}\``));
    else if (s.type === "kv") lines.push(...s.items.map((t) => `**${t.term}** — ${t.definition}`));
    else if (s.type === "qa")
      lines.push(
        ...s.items.map(
          (q, i) => `${i + 1}. ${q.meta ? `(${q.meta}) ` : ""}${q.question}\n   > ${q.answer}`,
        ),
      );
  }
  const blob = new Blob([lines.join("\n")], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${opts.title.replace(/[^\w\d -]/g, "").slice(0, 60) || "edspire-notes"}.md`;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}
