import type { ShortNotes } from "./mockData";

/**
 * Opens a print-styled window with the cheat sheet HTML and triggers the browser
 * print dialog so the user can save it as a PDF. Works on mobile & desktop without
 * bundling a PDF library.
 */
export function exportCheatSheetPdf(chapterTitle: string, notes: ShortNotes) {
  const win = window.open("", "_blank", "noopener,noreferrer,width=800,height=900");
  if (!win) return;

  const esc = (s: string) =>
    s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${esc(notes.title || chapterTitle)} — Cheat Sheet</title>
<style>
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color:#111; margin:0; padding:32px; line-height:1.5; }
  header { border-bottom:2px solid #111; padding-bottom:10px; margin-bottom:20px; }
  h1 { font-size:22px; margin:0; }
  .subtitle { font-size:12px; color:#666; margin-top:4px; }
  h2 { font-size:14px; text-transform:uppercase; letter-spacing:0.08em; margin:20px 0 8px; color:#222; border-left:3px solid #111; padding-left:8px; }
  ul { margin:0; padding-left:20px; }
  li { margin-bottom:6px; font-size:13px; }
  .formula { font-family: "SFMono-Regular", Menlo, monospace; background:#f4f4f5; border:1px solid #e4e4e7; border-radius:6px; padding:6px 10px; margin:4px 0; font-size:13px; }
  .term { margin-bottom:10px; font-size:13px; }
  .term b { display:block; margin-bottom:2px; }
  .tip { margin-top:24px; padding:12px; border:1px dashed #d97706; background:#fffbeb; border-radius:8px; font-size:13px; }
  footer { margin-top:32px; font-size:10px; color:#888; text-align:center; }
  @media print { body { padding:16mm; } }
</style>
</head>
<body>
  <header>
    <h1>${esc(notes.title || chapterTitle)}</h1>
    <div class="subtitle">${esc(chapterTitle)} · AI-generated cheat sheet</div>
  </header>

  ${notes.keyPoints?.length ? `<h2>Key Points</h2><ul>${notes.keyPoints.map((p) => `<li>${esc(p)}</li>`).join("")}</ul>` : ""}

  ${notes.formulas?.length ? `<h2>Formulas</h2>${notes.formulas.map((f) => `<div class="formula">${esc(f)}</div>`).join("")}` : ""}

  ${notes.keyTerms?.length ? `<h2>Key Terms</h2>${notes.keyTerms.map((t) => `<div class="term"><b>${esc(t.term)}</b>${esc(t.definition)}</div>`).join("")}` : ""}

  ${notes.rememberTip ? `<div class="tip"><b>Remember:</b> ${esc(notes.rememberTip)}</div>` : ""}

  <footer>Generated by Edspire Lens</footer>

  <script>
    window.addEventListener("load", () => {
      setTimeout(() => { window.print(); }, 250);
    });
  </script>
</body>
</html>`;

  win.document.open();
  win.document.write(html);
  win.document.close();
}